name: CDK Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

       # AWS configuration
      AWSRoleToAssume:
        description: AWS role ARN to assume. Should have a corresponding trust policy
        type: string
        required: false
      AWSRegion:
        default: us-east-2
        description: Which region to use in AWS. Signet standard is us-east-2
        type: string
        required: false
      AWSRoleDurationSeconds:
        description: How long the assumed role session lasts (in seconds)
        type: string
        default: "900"
      AWSRoleSessionName:
        default: github-action-assumed-role
        description: A "role session friendly name" to make deciphering logs easier
        type: string
      AWSMaskAccountId:
        default: true
        description: Whether to mask or not mask the AWS Account ID
        type: boolean


      nodeVersion:
        type: string
        default: "20"

      cdkVersion:
        type: string
        default: "latest"

      inputArtifactDownloadName:
        description: "Artifact name to download"
        type: string
        required: true

      deployArgs:
        description: "Additional CDK deploy arguments"
        type: string
        required: false
        default: ""

      stackName:
        description: "CDK stack name"
        type: string
        required: false
        default: ""

permissions:
  id-token: write
  contents: read
  actions: read

env:
  GH_RUN_NUM: ${{ github.run_number }}
  ENVIRONMENT: ${{ inputs.environment }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.AWSRegion }}
          role-duration-seconds: ${{ inputs.AWSRoleDurationSeconds }}
          role-session-name: ${{ inputs.AWSRoleSessionName }}
          role-to-assume: ${{ inputs.AWSRoleToAssume }}
          mask-aws-account-id: ${{ inputs.AWSMaskAccountId }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.inputArtifactDownloadName }}
          path: ./artifact

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}

      - name: Install CDK
        run: npm install -g aws-cdk@${{ inputs.cdkVersion }}

      - name: List Artifact Files
        run: ls -R ./artifact

      - name: Deploy CDK
        run: |
          cdk deploy \
            --app ./artifact \
            --require-approval never \
            ${{ inputs.deployArgs }} \
            ${{ inputs.stackName }}
