name: CDK Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

      AWSRoleToAssume:
        type: string
        required: true

      AWSRegion:
        type: string
        default: us-east-1

      AWSRoleDurationSeconds:
        type: string
        default: "900"

      AWSRoleSessionName:
        type: string
        default: github-cdk-deploy

      AWSMaskAccountId:
        type: boolean
        default: false

      nodeVersion:
        type: string
        default: "20"

      cdkVersion:
        type: string
        default: "latest"

      workingDirectory:
        type: string
        default: "./app"

      deployArgs:
        type: string
        required: false
        default: ""

      stackName:
        type: string
        required: false
        default: ""

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.AWSRegion }}
          role-to-assume: ${{ inputs.AWSRoleToAssume }}
          role-duration-seconds: ${{ inputs.AWSRoleDurationSeconds }}
          role-session-name: ${{ inputs.AWSRoleSessionName }}
          mask-aws-account-id: ${{ inputs.AWSMaskAccountId }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}

      - name: Install CDK
        run: npm install -g aws-cdk@${{ inputs.cdkVersion }}

      - name: Install Dependencies
        working-directory: ${{ inputs.workingDirectory }}
        run: |
          pip install -r requirements.txt

      - name: Debug Directory
        run: |
          pwd
          ls -R

      - name: Deploy CDK
        working-directory: ${{ inputs.workingDirectory }}
        run: |
          cdk deploy \
            --require-approval never \
            ${{ inputs.deployArgs }} \
            ${{ inputs.stackName }}
