name: Docker Build and Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      aws_environment:
        description: "Choose Environment"
        type: choice
        options: ['dev', 'stage', 'prod']
        default: 'dev'
        required: true
      instance_count:
        description: 'Number of EC2 instances (1-2)'
        type: choice
        options: ['1', '2']
        default: '1'
        required: true

  push:
    branches:
      - test

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  SetupEnvVars:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.aws_environment || 'dev' }}
    outputs:
      account_num: ${{ steps.account_num_step.outputs.account_num }}
    steps:
      - name: Set Account Number
        id: account_num_step
        run: echo "account_num=${{ vars.ACCOUNT_NUM }}" >> "$GITHUB_OUTPUT"

  get-run-id:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.get-run.outputs.run_id }}

    steps:
      - name: Get latest workflow run ID
        id: get-run
        run: |
          RUN_ID=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs \
            | jq '[.workflow_runs[]
                  | select(.name=="Run Docker Pipeline" and .conclusion=="success")]
                  | sort_by(.created_at)
                  | reverse
                  | .[0].id')

          echo "Latest run ID: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

  dockerBuild:
    needs: 
    - SetupEnvVars
    - get-run-id
    uses: Ggowthampatnaik/streamlit-ecr-deploy/.github/workflows/docker-build.yml@main
    with:
      AWSRoleToAssume: arn:aws:iam::493272324412:role/github-ecr-role
      AWSRegion: us-east-1
  
      ECRRepository: streamlit-ecr-deploy
      dockerImageName: ${{ needs.SetupEnvVars.outputs.account_num }}.dkr.ecr.us-east-1.amazonaws.com/streamlit-ecr-deploy:${{ github.run_number }}
  
      createECR: true
      ecrPolicyFile: policy.json
  
      preBuildCommand: |
        git fetch origin main
        git checkout origin/main -- app
  
      buildCommand: docker build -f ./app/Dockerfile -t $IMAGE_NAME ./app
  
      outputArtifactUploadName: scan_results
      outputArtifactPath: scan_results/
      outputArtifactRetention: 5
      inputArtifactDownloadName: scan_results

      run_id: ${{ needs.get-run-id.outputs.run_id }}
  
    secrets:
      orcaSecurityApiToken: ${{ secrets.ORCA_TOKEN }}
  synthApp:
    needs:
      - SetupEnvVars
      - dockerBuild

    uses: Ggowthampatnaik/streamlit-ecr-deploy/.github/workflows/cdkSynth.yml@v11.1.1

    with:
      environment: ${{ github.event.inputs.aws_environment || 'dev' }}

      AWSRegion: us-east-1
      AWSRoleToAssume: arn:aws:iam::${{ needs.SetupEnvVars.outputs.account_num }}:role/github-ecr-role
      AWSRoleSessionName: gha-cdk-synth
      AWSRoleDurationSeconds: 900
      AWSMaskAccountId: false

      workingDirectory: ./app

      outputArtifactUploadName: ${{ github.event.inputs.aws_environment || 'dev' }}-infra
      outputArtifactRetention: 5

      installCommand: |
        pip install -r requirements.txt

      preBuildCommand: |
        git fetch origin main
        git checkout origin/main -- app

      synthArgs: >
        -c env=${{ github.event.inputs.aws_environment || 'dev' }}
        -c instanceCount=${{ github.event.inputs.instance_count || '1' }}
        -c imageUri=${{ needs.SetupEnvVars.outputs.account_num }}.dkr.ecr.us-east-1.amazonaws.com/streamlit-ecr-deploy:${{ github.run_number }}

    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      orcaSecurityApiToken: ${{ secrets.ORCA_TOKEN }}
    

  deployApp:
    needs:
      - SetupEnvVars
      - dockerBuild
      - synthApp

    uses: Ggowthampatnaik/streamlit-ecr-deploy/.github/workflows/cdkDeploy.yml@v11.1.1
    with:
      environment: ${{ github.event.inputs.aws_environment || 'dev' }}

      AWSRegion: us-east-1
      AWSRoleToAssume: arn:aws:iam::${{ needs.SetupEnvVars.outputs.account_num }}:role/github-ecr-role
      AWSRoleSessionName: gha-cdk-deploy
      AWSRoleDurationSeconds: 900
      AWSMaskAccountId: false
      stackName: StreamlitEcsStack
      inputArtifactDownloadName: ${{ github.event.inputs.aws_environment || 'dev' }}-infra

      deployArgs: >
        -c env=${{ github.event.inputs.aws_environment || 'dev' }}
        -c instanceCount=${{ github.event.inputs.instance_count || '1' }}
        -c imageUri=${{ needs.SetupEnvVars.outputs.account_num }}.dkr.ecr.us-east-1.amazonaws.com/streamlit-ecr-deploy:${{ github.run_number }}

    secrets: inherit
