name: Docker Build and Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      aws_environment:
        description: "Choose Environment"
        type: choice
        options: ['dev', 'stage', 'prod']
        default: 'dev'
        required: true
      instance_count:
        description: 'Number of EC2 instances (1-2)'
        type: choice
        options: ['1', '2']
        default: '1'
        required: true

  push:
    branches:
      - test

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  SetupEnvVars:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.aws_environment || 'dev' }}
    outputs:
      account_num: ${{ steps.account_num_step.outputs.account_num }}
    steps:
      - name: Set Account Number
        id: account_num_step
        run: echo "account_num=${{ vars.ACCOUNT_NUM }}" >> "$GITHUB_OUTPUT"

  dockerBuild:
    needs: SetupEnvVars
    uses: Ggowthampatnaik/streamlit-ecr-deploy/.github/workflows/docker-build.yml@main
    with:
      AWSRoleToAssume: arn:aws:iam::493272324412:role/github-ecr-role
      AWSRegion: us-east-1

      ECRRepository: streamlit-ecr-deploy
      dockerImageName: ${{ needs.SetupEnvVars.outputs.account_num }}.dkr.ecr.us-east-1.amazonaws.com/streamlit-ecr-deploy:${{ github.run_number }}

      createECR: true
      ecrPolicyFile: policy.json
      
      preBuildCommand: |
        git fetch origin main
        git checkout origin/main -- app

      buildCommand: docker build -f ./app/Dockerfile -t $IMAGE_NAME ./app

      outputArtifactName: ${{ github.event.inputs.aws_environment || 'dev' }}-infra
      outputArtifactPath: cdk.out
      outputArtifactRetention: 5

    secrets:
      orcaSecurityApiToken: ${{ secrets.ORCA_TOKEN }}
  
  deployApp:
    needs:
      - SetupEnvVars
      - dockerBuild
    uses: Ggowthampatnaik/streamlit-ecr-deploy/.github/workflows/cdkDeploy.yml@v11.1.1
    with:
      environment: ${{ github.event.inputs.aws_environment || 'dev' }}

      AWSRegion: us-east-1
      AWSRoleToAssume: arn:aws:iam::493272324412:role/github-ecr-role
      AWSRoleSessionName: gha-build-github-ecr-role
      AWSRoleDurationSeconds: 900
      AWSMaskAccountId: false
      inputArtifactDownloadName: {{ github.event.inputs.aws_environment || 'dev' }}-infra

      # inputArtifactDownloadName: ${{ github.event.inputs.aws_environment || 'dev' }}-infra

      deployArgs: -c env=${{ github.event.inputs.aws_environment || 'dev' }} -c instanceCount=${{ github.event.inputs.instance_count || '1' }}
