name: Run Docker Pipeline

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      AWSRoleToAssume: arn:aws:iam::493272324412:role/github-ecr-role
      ECRRepository: streamlit-ecr-deploy
      dockerImageName: 493272324412.dkr.ecr.us-east-1.amazonaws.com/streamlit-ecr-deploy:latest
      createECR: true
      ecrPolicyFile: policy.json

      outputArtifactPath: scan_results/
      outputArtifactName: scan_results
      outputArtifactRetention: 5
      inputArtifactDownloadName: scan_results

    secrets:
      orcaSecurityApiToken: ${{ secrets.ORCA_TOKEN }}
